### ISSUE TITLE
Build fails on 13-CURRENT - depends on removed gets(3) function

### ISSUE THREAD

**Issue by woodsb02** [grehan-freebsd/grub2-bhyve#10]
emaste@ recently removed gets(3) from FreeBSD 13-CURRENT [1].

Now grub2-bhyve is failing to build [2].

[1] https://reviews.freebsd.org/rS351659
[2] https://www.mail-archive.com/freebsd-pkg-fallout@freebsd.org/msg1264597.html

**Comment by grehan-freebsd** [comment]
Just saw the msg about fgets() being a possible replacement so will look into that.

**Comment by sarcasticadmin** [comment]
I ran into this last weekend and raised this issue on the bugs.freebsd.org. See ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241168

**Comment by sarcasticadmin** [comment]
@woodsb02 just submitting a patch to the bugzilla issue

**Comment by woodsb02** [comment]
Thanks!
Peter - did you want to vet this patch before it gets committed?

**Comment by grehan-freebsd** [comment]
I had a look. grub2 doesn't use gets() at all so it's just an error in the glib header file as a result of gets being excised from FreeBSD. Commenting out the _GL_WARN_ON_USE macro for that is fine.

**Comment by sarcasticadmin** [comment]
Thanks for the quick feedback!

**Comment by woodsb02** [comment]
Thanks for the patch Robert. I have committed it to the ports tree now, but note that I made the patch apply for all operating system versions, not just FreeBSD 13-CURRENT.

Peter - did you want to continue to carry the patch locally in the ports tree, or include it in this upstream repo and cut a new release?

**Comment by grehan-freebsd** [comment]
I'll eventually include it here but the ports patch will be fine for now.

**Comment by grehan-freebsd** [comment]
Committed; will create a new release so the port can pull from that.
