### ISSUE TITLE
doesn't build on FreeBSD 10.3-RELEASE

### ISSUE THREAD

**Issue by kevingnet** [grehan-freebsd/grub2-bhyve#5]
Trying to build on FreeBSD 10.3-RELEASE gives:
var/src/grub2-bhyve-master # make
make: "/var/src/grub2-bhyve-master/Makefile" line 20789: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /var/src/grub2-bhyve-master
# :/var/src/grub2-bhyve-master # find /usr/ -name unexport
# :/var/src/grub2-bhyve-master # unexport

unexport: Command not found.

**Comment by grehan-freebsd** [comment]
You have to use gmake (make is FreeBSD make which has a different syntax).
