### ISSUE TITLE
check for TERM not set

### ISSUE THREAD

**Issue by swills** [grehan-freebsd/grub2-bhyve#9]
I ran into an issue where grub-bhyve was spinning using 100% cpu for me, which eventually lead me to discover this commit:

https://github.com/churchers/vm-bhyve/commit/24b6b35c2521cc3a40319a0beef5ceb8c64d1b1f

and to do something similar. Perhaps grub-bhyve should be changed to check for TERM not being set and default to xterm or complain to the user?

**Comment by grehan-freebsd** [comment]
That does indeed seem an issue. Let me see if I can come up with a simple fix.
